#!/bin/bash

# Remove mscoree from WINEDLLOVERRIDES to allow Logos9 to run.
#    (It's still needed before this point for wineprefix setup, though.)
export WINEDLLOVERRIDES=$(echo $WINEDLLOVERRIDES | sed -r 's/[,;]?mscoree[,;]?//')

if [[ "${ACTION_ARGS[$1]}" == '--version' ]]; then
    # Get Logos.exe version number from wine registry and exit.
    ver=$(grep "AssemblyVersion" "${SNAP_USER_COMMON}/.wine/user.reg" | awk -F= '{print $2}' | tr -d '"')
    if [[ -n "$ver" ]]; then
        echo "$ver"
        exit 0
    else
        echo "ERROR: Logos.exe version number not found."
        exit 1
    fi
fi

# Get Logos installation location.
LOGOS_EXE=$(find "${SNAP_USER_COMMON}/.wine" -name Logos.exe | grep /Logos/Logos.exe)
LOGOS_INSTALL_DIR=$(dirname "$LOGOS_EXE")
# Handle alternative executables.
EXE_DIR_PATH=$(dirname "$RUN_EXE")
EXE_DIR_NAME=$(basename "$EXE_DIR_PATH")
EXE=$(basename "$RUN_EXE")

# Determine whether running under strict confinement or not.
STRICT=1
cat /etc/fstab >/dev/null 2>&1
if [[ $? -eq 0 ]]; then
    STRICT=0
fi
if [[ "$EXE_DIR_NAME" == 'System' && "$EXE" == 'Logos.exe' ]]; then
    # Typical logos9 launch. Check if first run.
    if [[ ! -e "$RUN_EXE" ]]; then
        # First run.
        echo "First run; finishing setup with ${LOGOS_INSTALL_DIR}/Logos.exe."
        cd "$LOGOS_INSTALL_DIR"
        "$WINELOADER" "$EXE"
    fi
    # echo "Normal launch; checking for user account..."
    # # Check if user account already added.
    # if [[ ! -e "${LOGOS_INSTALL_DIR}/Users/UserMetadata" && "$STRICT" -eq 1 ]]; then
    #     # Extra launch on first run if no Logos/Users/UserMetadata file and
    #     #   if running under strict confinement.
    #     echo "No user account; finishing setup with Logos/Logos.exe."
    #     cd "$LOGOS_INSTALL_DIR"
    #     "$WINELOADER" "$EXE"
    # fi
    # Switch to running Logos/System/Logos.exe.
    # echo "Starting Logos/System/Logos.exe."
    # RUN_EXE=$("$WINELOADER" winepath "$RUN_EXE")
elif [[ "$EXE" == 'LogosIndexer.exe' ]]; then
    # Get user ID and Language info for LogosIndexer.exe.
    LOGOS_USER_ID=$(sed -r 's|.*"id":"([0-9a-z\.]{3,})",.*|\1|' "${LOGOS_INSTALL_DIR}/Users/UserMetadata")
    LOGOS_USER_LANG=$(grep 'ResourceTitleLanguage' "${SNAP_USER_COMMON}/.wine/user.reg" | awk -F= '{print $2}' | tr -d '"')
    # export LOGOS_USER_LANG=$(grep 'ResourceTitleLanguage' "${SNAP_USER_COMMON}/.wine/user.reg" | sed -r 's|"ResourceTitleLanguage"="(.*)"|\1|')
    ACTION_ARGS=( "/user:$LOGOS_USER_ID" "/lang:$LOGOS_USER_LANG" )
elif [[ "$EXE" == 'LogosUpdater.exe' ]]; then
    echo "WARNING: Running LogosUpdater.exe is currently experimental."
fi
